accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import create_user

urlpatterns = [
    path("login/", LoginView.as_view(), name = "login"),
    path("logout/",LogoutView.as_view(), name= "logout"),
    path("signup/", create_user, name = "signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include("receipts.urls")),
    path('accounts/', include("accounts.urls")),
    path("",RedirectView.as_view(url = reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import ReceiptListView, ReceiptCreateView, ExpenseCategoryListView, AccountListView, ExpenseCategoryCreateView, AccountCreateView

urlpatterns = [
    path("",ReceiptListView.as_view(), name = "home"),
    path("categories/", ExpenseCategoryListView.as_view(), name = "list_categories"),
    path("accounts/", AccountListView.as_view(), name = "account_list_view"),
    path("create/", ReceiptCreateView.as_view(), name = "create_receipt"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name = "create_category"),
    path("accounts/create/", AccountCreateView.as_view(), name = "create_account"),

]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL,related_name="categories", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(USER_MODEL, related_name="accounts", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10,decimal_places=3)
    tax = models.DecimalField(max_digits=10,decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(USER_MODEL, related_name="receipts", on_delete=models.CASCADE)
    category = models.ForeignKey("ExpenseCategory", related_name="receipts", on_delete=models.CASCADE,null=True)
    account = models.ForeignKey("Account", related_name="receipts", on_delete=models.CASCADE, null=True)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

# Create your views here.

def create_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from receipts.models import Receipt, ExpenseCategory, Account
from pprint import pprint

# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"
    paginate_by = 10

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expenselist.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accountlist.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

class ReceiptCreateView(LoginRequiredMixin,CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    def form_valid(self,form):
        form.instance.purchaser=self.request.user
        return super().form_valid(form)

class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/newexpense.html"
    fields = ["name"]
    success_url = reverse_lazy("list_categories")

    def form_valid(self,form):
        form.instance.owner=self.request.user
        return super().form_valid(form)

class AccountCreateView(CreateView):
    model = Account
    template_name = "receipts/newaccount.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("account_list_view")

    def form_valid(self,form):
        form.instance.owner=self.request.user
        return super().form_valid(form)

receipts/templates/receipts/accountlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated%}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'create_account' %}">Create New Account</a></li>
                {% else %}
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>My Accounts</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            <tbody>
            {%for account in account_list %}
            <tr>
                <td>{{account.name}}</td>
                <td>{{account.number}}</td>
                <td>{{account.receipts.all|length}}</td>
            </tr>
            {%endfor%}
        </tbody>
        </table>
    </main>
</body>
</html>

receipts/templates/receipts/expenselist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated%}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'create_category' %}">Create</a></li>
                {% else %}
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>My Expenses</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            <tbody>
            {%for category in expensecategory_list %}
            <tr>
                <td>{{category.name}}</td>
                <td>{{category.receipts.all|length}}</td>
            </tr>
            {%endfor%}
        </tbody>
        </table>
    </main>
</body>
</html>

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated%}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'create_receipt' %}">Create New Receipt</a></li>
                {% else %}
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
            {%for item in receipt_list%}
            <tr>
                <td>{{item.vendor}}</td>
                <td>{{item.total}}</td>
                <td>{{item.tax}}</td>
                <td>{{item.date|date:"m-d-Y"}}</td>
                <td>{{item.category}}</td>
                <td>{{item.account}}</td>
            </tr>
            {%endfor%}
        </tbody>
        </table>
    </main>
</body>
</html>

receipts/templates/receipts/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Receipt</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated%}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method = "post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>

</body>
</html>

receipts/templates/receipts/newaccount.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated%}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Create Account</h1>
            <form method = "post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>

</body>
</html>

receipts/templates/receipts/newexpense.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Category</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated%}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
            <h1>Create Category</h1>
            <form method = "post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>

</body>
</html>